name: ORDER

on:
  push:
    branches: [ master ]

jobs:
  order:
    runs-on: ubuntu-latest

    steps:
    - name: Order the folder
      run: bash ./order img/
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        ...
    - name: Commit files
      run: |
        git config --local user.email "order@action.com"
        git config --local user.name "order action"
        git commit -m "ordered files" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
   

    
